[package]
name = "flipper"
version = "0.1.0"
authors = [ "George Morgan <george@george-morgan.com>",
            "Nick Mosher <nicholastmosher@gmail.com>" ]

[lib]
name = "flipper"
path = "src/lib.rs"

[dependencies]
libc = "0.2.0"
log = "0.4.1"